name: get_arch_core
description: dart architecture package, Inspired by Explicit Architecture, Clean Architectures, DDD,
version: 3.0.0
homepage: https://github.com/Hu-Wentao/get_arch_core

environment:
  sdk: '>=2.16.0-134.5.beta <3.0.0'

dependencies:
  get_it: ^7.0.0
  rxdart: ^0.27.1
  dartz: ^0.10.0
  equatable: ^2.0.3
  injectable: ^1.5.0
  supercharged_dart: ^2.0.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  build_runner:
  pubspec_generator: